include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unintended_html_in_doc_comment: ignore
    file_names: ignore
    avoid_print: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
